# Generated by Django 3.2.3 on 2021-05-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterpost',
            old_name='title',
            new_name='name',
        ),
    ]
